name: markingSystem
port: 9000

log4js:
  appenders:
    #name of appenders
    stdout:
      type: stdout
  categories:
    default:
      appenders: [stdout]
      level: debug

mysql:
  host: "47.94.151.34"
  user: test
  password: "test123456"
  database: test

#jwt secret key  二选一
#secretKeyPath: /path/to/public.pub
secretKey: "marking system jwt secret_key"